-- TPC-H Schema for PostgreSQL (Idempotent Version)
-- Based on TPC-H Standard Specification Revision 3.0.1

-- Drop existing tables in reverse order of dependency to avoid foreign key errors
DROP TABLE IF EXISTS LINEITEM CASCADE;
DROP TABLE IF EXISTS ORDERS CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS PARTSUPP CASCADE;
DROP TABLE IF EXISTS SUPPLIER CASCADE;
DROP TABLE IF EXISTS PART CASCADE;
DROP TABLE IF EXISTS NATION CASCADE;
DROP TABLE IF EXISTS REGION CASCADE;


-- Table: REGION
CREATE TABLE REGION (
    R_REGIONKEY INTEGER NOT NULL,
    R_NAME      CHAR(25) NOT NULL,
    R_COMMENT   VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY)
);

-- Table: NATION
CREATE TABLE NATION (
    N_NATIONKEY INTEGER NOT NULL,
    N_NAME      CHAR(25) NOT NULL,
    N_REGIONKEY INTEGER NOT NULL,
    N_COMMENT   VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY)
);

-- Table: PART
CREATE TABLE PART (
    P_PARTKEY     BIGINT NOT NULL,
    P_NAME        VARCHAR(55) NOT NULL,
    P_MFGR        CHAR(25) NOT NULL,
    P_BRAND       CHAR(10) NOT NULL,
    P_TYPE        VARCHAR(25) NOT NULL,
    P_SIZE        INTEGER NOT NULL,
    P_CONTAINER   CHAR(10) NOT NULL,
    P_RETAILPRICE DECIMAL(10, 2) NOT NULL,
    P_COMMENT     VARCHAR(23) NOT NULL,
    PRIMARY KEY (P_PARTKEY)
);

-- Table: SUPPLIER
CREATE TABLE SUPPLIER (
    S_SUPPKEY   BIGINT NOT NULL,
    S_NAME      CHAR(25) NOT NULL,
    S_ADDRESS   VARCHAR(40) NOT NULL,
    S_NATIONKEY INTEGER NOT NULL,
    S_PHONE     CHAR(15) NOT NULL,
    S_ACCTBAL   DECIMAL(10, 2) NOT NULL,
    S_COMMENT   VARCHAR(101) NOT NULL,
    PRIMARY KEY (S_SUPPKEY)
);

-- Table: PARTSUPP
CREATE TABLE PARTSUPP (
    PS_PARTKEY    BIGINT NOT NULL,
    PS_SUPPKEY    BIGINT NOT NULL,
    PS_AVAILQTY   INTEGER NOT NULL,
    PS_SUPPLYCOST DECIMAL(10, 2) NOT NULL,
    PS_COMMENT    VARCHAR(199) NOT NULL,
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    C_CUSTKEY    BIGINT NOT NULL,
    C_NAME       VARCHAR(25) NOT NULL,
    C_ADDRESS    VARCHAR(40) NOT NULL,
    C_NATIONKEY  INTEGER NOT NULL,
    C_PHONE      CHAR(15) NOT NULL,
    C_ACCTBAL    DECIMAL(10, 2) NOT NULL,
    C_MKTSEGMENT CHAR(10) NOT NULL,
    C_COMMENT    VARCHAR(117) NOT NULL,
    PRIMARY KEY (C_CUSTKEY)
);

-- Table: ORDERS
CREATE TABLE ORDERS (
    O_ORDERKEY      BIGINT NOT NULL,
    O_CUSTKEY       BIGINT NOT NULL,
    O_ORDERSTATUS   CHAR(1) NOT NULL,
    O_TOTALPRICE    DECIMAL(10, 2) NOT NULL,
    O_ORDERDATE     DATE NOT NULL,
    O_ORDERPRIORITY CHAR(15) NOT NULL,
    O_CLERK         CHAR(15) NOT NULL,
    O_SHIPPRIORITY  INTEGER NOT NULL,
    O_COMMENT       VARCHAR(79) NOT NULL,
    PRIMARY KEY (O_ORDERKEY)
);

-- Table: LINEITEM
CREATE TABLE LINEITEM (
    L_ORDERKEY      BIGINT NOT NULL,
    L_PARTKEY       BIGINT NOT NULL,
    L_SUPPKEY       BIGINT NOT NULL,
    L_LINENUMBER    INTEGER NOT NULL,
    L_QUANTITY      DECIMAL(10, 2) NOT NULL,
    L_EXTENDEDPRICE DECIMAL(10, 2) NOT NULL,
    L_DISCOUNT      DECIMAL(10, 2) NOT NULL,
    L_TAX           DECIMAL(10, 2) NOT NULL,
    L_RETURNFLAG    CHAR(1) NOT NULL,
    L_LINESTATUS    CHAR(1) NOT NULL,
    L_SHIPDATE      DATE NOT NULL,
    L_COMMITDATE    DATE NOT NULL,
    L_RECEIPTDATE   DATE NOT NULL,
    L_SHIPINSTRUCT  CHAR(25) NOT NULL,
    L_SHIPMODE      CHAR(10) NOT NULL,
    L_COMMENT       VARCHAR(44) NOT NULL,
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

-- Foreign Key Constraints
ALTER TABLE NATION
    ADD CONSTRAINT fk_nation_region FOREIGN KEY (N_REGIONKEY) REFERENCES REGION (R_REGIONKEY);
ALTER TABLE SUPPLIER
    ADD CONSTRAINT fk_supplier_nation FOREIGN KEY (S_NATIONKEY) REFERENCES NATION (N_NATIONKEY);
ALTER TABLE PARTSUPP
    ADD CONSTRAINT fk_partsupp_part FOREIGN KEY (PS_PARTKEY) REFERENCES PART (P_PARTKEY);
ALTER TABLE PARTSUPP
    ADD CONSTRAINT fk_partsupp_supplier FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER (S_SUPPKEY);
ALTER TABLE CUSTOMER
    ADD CONSTRAINT fk_customer_nation FOREIGN KEY (C_NATIONKEY) REFERENCES NATION (N_NATIONKEY);
ALTER TABLE ORDERS
    ADD CONSTRAINT fk_orders_customer FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER (C_CUSTKEY);
ALTER TABLE LINEITEM
    ADD CONSTRAINT fk_lineitem_orders FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS (O_ORDERKEY);
ALTER TABLE LINEITEM
    ADD CONSTRAINT fk_lineitem_partsupp FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP (PS_PARTKEY, PS_SUPPKEY);