# Central repository for TPC-H table schemas with data types.
TPCH_SCHEMA = {
    "region": {
        "columns": ["r_regionkey", "r_name", "r_comment"],
        "types": ["int", "str", "str"],
        "pk": "r_regionkey",
    },
    "nation": {
        "columns": ["n_nationkey", "n_name", "n_regionkey", "n_comment"],
        "types": ["int", "str", "int", "str"],
        "pk": "n_nationkey",
    },
    "part": {
        "columns": [
            "p_partkey",
            "p_name",
            "p_mfgr",
            "p_brand",
            "p_type",
            "p_size",
            "p_container",
            "p_retailprice",
            "p_comment",
        ],
        "types": [
            "int",
            "str",
            "str",
            "str",
            "str",
            "int",
            "str",
            "decimal",
            "str",
        ],  # noqa:F501
        "pk": "p_partkey",
    },
    "supplier": {
        "columns": [
            "s_suppkey",
            "s_name",
            "s_address",
            "s_nationkey",
            "s_phone",
            "s_acctbal",
            "s_comment",
        ],
        "types": ["int", "str", "str", "int", "str", "decimal", "str"],
        "pk": "s_suppkey",
    },
    "partsupp": {
        "columns": [
            "ps_partkey",
            "ps_suppkey",
            "ps_availqty",
            "ps_supplycost",
            "ps_comment",
        ],
        "types": ["int", "int", "int", "decimal", "str"],
        "pk": ["ps_partkey", "ps_suppkey"],
    },
    "customer": {
        "columns": [
            "c_custkey",
            "c_name",
            "c_address",
            "c_nationkey",
            "c_phone",
            "c_acctbal",
            "c_mktsegment",
            "c_comment",
        ],
        "types": ["int", "str", "str", "int", "str", "decimal", "str", "str"],
        "pk": "c_custkey",
    },
    "orders": {
        "columns": [
            "o_orderkey",
            "o_custkey",
            "o_orderstatus",
            "o_totalprice",
            "o_orderdate",
            "o_orderpriority",
            "o_clerk",
            "o_shippriority",
            "o_comment",
        ],
        "types": [
            "int",
            "int",
            "str",
            "decimal",
            "date",
            "str",
            "str",
            "int",
            "str",
        ],  # noqa:F501
        "pk": "o_orderkey",
    },
    "lineitem": {
        "columns": [
            "l_orderkey",
            "l_partkey",
            "l_suppkey",
            "l_linenumber",
            "l_quantity",
            "l_extendedprice",
            "l_discount",
            "l_tax",
            "l_returnflag",
            "l_linestatus",
            "l_shipdate",
            "l_commitdate",
            "l_receiptdate",
            "l_shipinstruct",
            "l_shipmode",
            "l_comment",
        ],
        "types": [
            "int",
            "int",
            "int",
            "int",
            "decimal",
            "decimal",
            "decimal",
            "decimal",
            "str",
            "str",
            "date",
            "date",
            "date",
            "str",
            "str",
            "str",
        ],
        "pk": ["l_orderkey", "l_linenumber"],
    },
    "sales": {
        "columns": ["sale_id", "amount", "sale_date"],
        "types": ["int", "decimal", "date"],
        "pk": "sale_id",
    },
}

TPCH_TABLE_ORDER = [
    "region",
    "nation",
    "supplier",
    "customer",
    "part",
    "partsupp",
    "orders",
    "lineitem",
]
